<!-- markdownlint-disable MD024 MD025 -->

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

# 0 0 0 0 0 0

<b><font color="#ED5E5E">YANKED!</font></b> Initial release of the application
