---
title: Latest Commit
---

## **Summary**

<!-- cspell: disable-next-line -->
Yet 'nother fucking oopsies...

## **Changes**

<!--

Added
    For adding new features.
Changed
    For changes in existing functionality.
Deprecated
    For marking features as `deprecated`.
Removed
    For removing features.
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
-->

- `docs/now.md` for what {{author}} is doing after or during the latest commit
- `no_implicit_optional` and `ruff` as dev requirements

### **Changed**

<!--
For changes in existing functionality.
-->

- `.gitattributes` for more accurate language stats
- `dev/scripts/py/docs.py` so that markdown files with no lower than h4 should not be subjected to the horrible workaround of styling headers just to support 'til "h11" ???

### **Deprecated**

<!--
For marking features as `deprecated`.
-->

### **Removed**

<!--
For removing features.
-->

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->