name: Latest Commit Comment

on:
  push:
    paths:
      - dev/raw_docs/latest-commit.mmd
  workflow_dispatch:

jobs:
  Comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - id: get-comment-body
        run: |
          body=$(cat "docs/latest-commit.md")
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: ${{ steps.get-comment-body.outputs.body }}